import * as functions from "firebase-functions";
import * as admin from "firebase-admin";
import * as os from "os";
import * as path from "path";
import * as fs from "fs";

const db = admin.firestore();
const storage = admin.storage();

// epson-connect-js は CommonJS (型定義なし)
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { Client } = require("epson-connect-js");

interface PrintSettings {
  media_size?: string;
  media_type?: string;
  borderless?: boolean;
  print_quality?: string;
  color_mode?: string;
  two_sided?: string;
  copies?: number;
}

/**
 * Epson Connect の認証情報をFirestoreから取得
 */
async function getEpsonCredentials(
  uid: string
): Promise<{ printerEmail: string; clientId: string; clientSecret: string }> {
  const doc = await db.collection("epsonConnectSettings").doc(uid).get();
  if (!doc.exists) {
    throw new functions.https.HttpsError(
      "failed-precondition",
      "Epson Connect の設定がされていません。設定ページで接続情報を登録してください。"
    );
  }
  const data = doc.data()!;
  if (!data.printerEmail || !data.clientId || !data.clientSecret) {
    throw new functions.https.HttpsError(
      "failed-precondition",
      "Epson Connect の接続情報が不完全です。設定ページで確認してください。"
    );
  }
  return {
    printerEmail: data.printerEmail,
    clientId: data.clientId,
    clientSecret: data.clientSecret,
  };
}

/**
 * テキストコンテンツをPDFファイルに変換
 */
async function generatePdf(
  content: string,
  title: string
): Promise<string> {
  const PDFDocument = require("pdfkit");

  return new Promise((resolve, reject) => {
    const tmpFilePath = path.join(os.tmpdir(), `creative-${Date.now()}.pdf`);
    const doc = new PDFDocument({
      size: "A4",
      margin: 60,
      info: { Title: title },
    });

    const stream = fs.createWriteStream(tmpFilePath);
    doc.pipe(stream);

    // 日本語フォントの登録（Cloud Functions環境ではNoto Sans JPが利用可能な場合あり）
    // フォールバックとしてHelveticaを使用
    const fontPath = "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc";
    if (fs.existsSync(fontPath)) {
      doc.font(fontPath);
    }

    // タイトル
    doc.fontSize(18).text(title, { align: "center" });
    doc.moveDown(1.5);

    // 本文
    doc.fontSize(11).text(content, {
      align: "left",
      lineGap: 6,
    });

    // フッター
    doc.moveDown(2);
    doc
      .fontSize(8)
      .fillColor("#999")
      .text("Generated by AIOPress", { align: "center" });

    doc.end();

    stream.on("finish", () => resolve(tmpFilePath));
    stream.on("error", reject);
  });
}

/**
 * Cloud Storageの画像をローカルにダウンロード
 */
async function downloadImageToTmp(imageUrl: string): Promise<string> {
  const bucket = storage.bucket();

  // Cloud Storage URLからパスを抽出
  const urlObj = new URL(imageUrl);
  const storagePath = decodeURIComponent(
    urlObj.pathname.replace(`/${bucket.name}/`, "")
  );
  const ext = path.extname(storagePath) || ".png";
  const tmpFilePath = path.join(os.tmpdir(), `print-${Date.now()}${ext}`);

  await bucket.file(storagePath).download({ destination: tmpFilePath });
  return tmpFilePath;
}

/**
 * クリエイティブを印刷する Cloud Function
 */
export const printCreative = functions
  .region("asia-northeast1")
  .runWith({ timeoutSeconds: 120, memory: "512MB" })
  .https.onCall(async (data, context) => {
    if (!context.auth) {
      throw new functions.https.HttpsError(
        "unauthenticated",
        "認証が必要です"
      );
    }

    const { creativeId, printSettings } = data as {
      creativeId: string;
      printSettings?: PrintSettings;
    };

    if (!creativeId) {
      throw new functions.https.HttpsError(
        "invalid-argument",
        "creativeId が必要です"
      );
    }

    const uid = context.auth.uid;

    // 1. クリエイティブを取得
    const creativeDoc = await db.collection("creatives").doc(creativeId).get();
    if (!creativeDoc.exists) {
      throw new functions.https.HttpsError(
        "not-found",
        "クリエイティブが見つかりません"
      );
    }
    const creative = creativeDoc.data()!;

    // ブランドメンバーか確認
    const { verifyBrandMember } = require("./utils");
    await verifyBrandMember(creative.brandId, uid);

    // 2. Epson Connect 認証情報を取得
    const credentials = await getEpsonCredentials(uid);

    // 3. 印刷対象ファイルを準備
    let filePath: string;
    let printMode: string;
    let tmpFile: string | null = null;

    if (creative.type === "IMAGE" && creative.imageUrl) {
      // 画像の場合: Cloud Storageからダウンロード
      try {
        filePath = await downloadImageToTmp(creative.imageUrl);
        tmpFile = filePath;
        printMode = "photo";
      } catch (_downloadError) {
        // 公開URLの場合はそのまま渡す（epson-connect-jsがHTTP URLを直接処理可能）
        filePath = creative.imageUrl;
        printMode = "photo";
      }
    } else {
      // テキスト系の場合: PDFを生成
      const title =
        creative.type === "CATCH_COPY"
          ? "キャッチコピー"
          : creative.type === "SNS_POST"
          ? "SNS投稿"
          : creative.type === "ARTICLE"
          ? "記事"
          : "クリエイティブ";

      filePath = await generatePdf(creative.content, title);
      tmpFile = filePath;
      printMode = "document";
    }

    try {
      // 4. Epson Connect クライアントを初期化
      const client = new Client(
        credentials.printerEmail,
        credentials.clientId,
        credentials.clientSecret
      );
      await client.initialize();

      // 5. 印刷設定
      const settings: Record<string, unknown> = {
        job_name: `AIOPress-${creative.type}-${Date.now()}`,
        print_mode: printMode,
        print_setting: {
          media_size: printSettings?.media_size || "ms_a4",
          media_type:
            printSettings?.media_type ||
            (printMode === "photo" ? "mt_photopaper" : "mt_plainpaper"),
          borderless: printSettings?.borderless || false,
          print_quality: printSettings?.print_quality || "normal",
          source: "auto",
          color_mode: printSettings?.color_mode || "color",
          two_sided: printSettings?.two_sided || "none",
          copies: printSettings?.copies || 1,
          collate: true,
        },
      };

      // 6. 印刷実行
      const jobId = await client.printer.print(filePath, settings);

      // 7. 認証解除
      await client.deauthenticate();

      // 8. 印刷履歴をFirestoreに保存
      await db.collection("printJobs").add({
        creativeId,
        brandId: creative.brandId,
        userId: uid,
        jobId,
        settings,
        status: "submitted",
        createdAt: admin.firestore.FieldValue.serverTimestamp(),
      });

      return {
        success: true,
        jobId,
        message: "印刷ジョブを送信しました",
      };
    } catch (error: any) {
      console.error("Epson Connect print error:", error);
      throw new functions.https.HttpsError(
        "internal",
        "印刷に失敗しました。Epson Connect の接続設定を確認してください。"
      );
    } finally {
      // 一時ファイルを削除
      if (tmpFile && fs.existsSync(tmpFile)) {
        fs.unlinkSync(tmpFile);
      }
    }
  });

/**
 * Epson Connect 設定を保存する Cloud Function
 */
export const saveEpsonSettings = functions
  .region("asia-northeast1")
  .https.onCall(async (data, context) => {
    if (!context.auth) {
      throw new functions.https.HttpsError(
        "unauthenticated",
        "認証が必要です"
      );
    }

    const { printerEmail, clientId, clientSecret } = data as {
      printerEmail: string;
      clientId: string;
      clientSecret: string;
    };

    if (!printerEmail || !clientId || !clientSecret) {
      throw new functions.https.HttpsError(
        "invalid-argument",
        "printerEmail, clientId, clientSecret が必要です"
      );
    }

    // 接続テスト
    try {
      const client = new Client(printerEmail, clientId, clientSecret);
      await client.initialize();
      const printerInfo = await client.printer.info();
      await client.deauthenticate();

      // 設定をFirestoreに保存
      await db.collection("epsonConnectSettings").doc(context.auth.uid).set(
        {
          printerEmail,
          clientId,
          clientSecret,
          printerName: printerInfo.printer_name || "",
          connectionStatus: "connected",
          updatedAt: admin.firestore.FieldValue.serverTimestamp(),
        },
        { merge: true }
      );

      return {
        success: true,
        printerName: printerInfo.printer_name || "不明",
        message: "Epson Connect に接続しました",
      };
    } catch (error: any) {
      console.error("Epson Connect connection test failed:", error);
      throw new functions.https.HttpsError(
        "invalid-argument",
        "接続テストに失敗しました。認証情報を確認してください。"
      );
    }
  });

/**
 * Epson Connect 設定を取得する Cloud Function
 */
export const getEpsonSettings = functions
  .region("asia-northeast1")
  .https.onCall(async (_data, context) => {
    if (!context.auth) {
      throw new functions.https.HttpsError(
        "unauthenticated",
        "認証が必要です"
      );
    }

    const doc = await db
      .collection("epsonConnectSettings")
      .doc(context.auth.uid)
      .get();

    if (!doc.exists) {
      return { success: true, configured: false };
    }

    const data = doc.data()!;
    return {
      success: true,
      configured: true,
      printerEmail: data.printerEmail || "",
      printerName: data.printerName || "",
      connectionStatus: data.connectionStatus || "unknown",
    };
  });
